TakwimuAfrica/Takwimu.AFRICA

- README.md
- package.json
- scripts/chartsDefinitionsApplyUniqueId.js
- src/App.js
- src/components/ChartFactory.js
- src/components/ProfileDetail/index.js
- src/config.js
- src/data/chart.json
- src/data/queries.js
- src/data/useChartDefinitions.js
- src/data/useProfileLoader.js
- src/pages/Embed.js
- src/pages/Profile.js
- src/setupProxy.js
- yarn.lock
Embed:
```
<iframe src="http://localhost:3000/embed/country-SN/elections/valid-vs-invalid-votes/" />
```
> Embed page + Population detail on profile detail component

- src/components/ChartFactory.js
- src/components/ProfileDetail/index.js
- src/config.js
- src/data/chart.json
- src/data/queries.js
- src/data/sources.json
- src/pages/Profile.js
- yarn.lock
> [Bugs] Small Fixes and Updates

- pages/index.js
- src/components/Next/Home.js
- src/config.js
> [Hotfix] Switch mailing list address

- pages/index.js
- src/components/LatestNewsStories/StoryBlocks.js
- src/components/LatestNewsStories/StoryCard.js
- src/components/LatestNewsStories/StoryList.js
- src/components/LatestNewsStories/StorySummary.js
> Fetch medium stories

- pages/_document.js
- pages/profiles/[geoIdOrCountrySlug]/index.js
> Performance boost using Lighthouse tips

- src/common.js
- src/components/DataContainer/FlourishChart.js
- src/components/DataContainer/HURUmapChart.js
- src/pages/Profile.js
Enable sharing on Flourish & HURUmap charts on **Featured Data** section and **Country Analysis** and **Data by Topic** pages.
> Sharing is Caring

- package.json
- yarn.lock
> [Hotfix] Switch to `now` for deployment

- src/components/DataContainer/FlourishChart.js
- src/config.js
Flourish charts need to processed after the iframe has loaded to enable:
> [Hotfix] Flourish Frame Styling

- src/components/DataContainer/FlourishChart.js
- yarn.lock
- `iframe` download has been fixed in HURUmap-UI,
- Flourish chart in the dashboard now include styling script,
- Updates all other dependencies.
NA
> [Hotfix] Upgrade HURUmap-UI

- src/components/AnalysisPage.js
- src/pages/[page]/[post]/index.js
- src/pages/[page]/index.js
- src/theme.js
Load script to replace hurumap card divs from wordpress.
> Load hurumap-ui micro-frontend script

- src/config.js
- src/pages/robots.txt.js
Disable site crawling on dev hosts:
- `dev.takwimu.africa`, and
- `now.sh`
The hosts as well as `robots.txt` are all configurable.
> Robot Wars

- yarn.lock
Upgrade dependencies due to security alert
N/A
> [Hotfix] yarn upgrade

- src/components/AnalysisPage.js
Discontinue using ACF geography field.
> Deprecate ACF geography in the frontend

- src/components/ProfileDetail/index.js
Fixes font and spacing to closely match designs.
> [Hotfix] Profile Detail Header

- src/pages/_document.js
Adds **Muli:600** to the google fonts link
N/A
> [Hotfix] semibold Muli font

- src/components/Next/Card.js
> [Hotfix] Where to Next

- src/components/AnalysisContent/index.js
- src/components/AnalysisPage.js
- src/components/CountryContent/Selection.js
- src/components/CountryContent/index.js
Update analysis or data by topic component selector
Please delete options that are not relevant.
> Analysis & Data by Topic component selector

- src/components/AnalysisPage.js
- src/components/LatestNewsStories/Story.js
- src/components/LatestNewsStories/StoryBlocks.js
- src/components/LatestNewsStories/StoryCard.js
- src/components/LatestNewsStories/StoryList.js
- src/components/LatestNewsStories/index.js
- src/pages/[page]/[post]/index.js
- src/pages/_app.js
- src/pages/_document.js
- src/theme.js
> [Hotfix] Latest News & Stories

- src/components/Hero.js
> [Hotfix] Hero

- src/components/AnalysisContent/index.js
- src/components/AnalysisPage.js
- src/components/CountryContent/Selection.js
- src/components/CountryContent/index.js
> Analysis / Data by Topic component selector

- src/cms.js
Filter only sectioned hurumap charts for data by topics
Fixes [#170892637](https://www.pivotaltracker.com/story/show/170892637)
> [HotFix] Filter hurumap charts for data by topics

- src/components/FeaturedAnalysis/CurrentAnalysis.js
[x] Adjust lineHeight for content area according to design
[x] `2px solid` border for button during inactive and onHover state
Fixes [#170767672](https://www.pivotaltracker.com/story/show/170767672)
> Featured Analyis: Adjust lineHeight + 2px solid border for button

- src/components/ProfilePage.js
Show chart source from the updated `useProfileLoader`
Fixes #[170916580](https://www.pivotaltracker.com/story/show/170916580)
> [HotFix] Fix chart source on Data by Topic page

- src/config.js
Update Kenya's population to use latest census (2019)
Fixes [#170921031](https://www.pivotaltracker.com/story/show/170921031)
> [HotFix]  Kenya population to use Census 2019

- src/components/AnalysisContent/Actions/DownloadPDF.js
- src/components/Footer/index.js
Don't forget when we started: https://stackoverflow.com/a/2391555/1298144
N/A
> [Hotfix] Year 2018-2018

- src/components/SearchInput/Input.js
- src/components/SearchInput/index.js
- src/components/SearchResults/SearchResultsContainer.js
Search results font styling + padding sizes
Fixes [#170792033](https://www.pivotaltracker.com/story/show/170792033)
> Fix Search Results Font Styling

- src/components/Navigation/DropDownButton.js
- src/components/Navigation/DropDownDrawer.js
> Fix background css

- src/components/ContactContent/TableOfContent.js
- src/components/ContactContent/index.js
- src/components/ContentPage.js
- src/components/RichTextSection.js
- src/components/TableOfContent.js
Fix contact page 
Fixes [#170791986](https://www.pivotaltracker.com/story/show/170791986)
> Fix contact content

- src/assets/images/search-black.svg
- src/components/SearchInput/Input.js
> [Hotfix] Search Input

- src/components/ProfilePage.js
- src/theme.js
- yarn.lock
> [Hotfix] Data by ... Tweaks

- src/components/CountryContent/index.js
Fix component spacing and fonts
> [Hotfix] Country Content Component

- Procfile
- app.json
- package.json
- src/components/AnalysisContent/index.js
- src/components/CountryContent/index.js
- src/components/LatestNewsStories/StoryCard.js
- src/pages/profiles/[geoIdOrCountrySlug]/index.js
- src/theme.js
- yarn.lock
Fix some inconsistent alignments
Fix blocks not rendering when switching between topics
> Dokku + UI fixes

- package.json
- src/components/ProfilePage.js
- yarn.lock
Enable the Show Data action button to show rawData on a DataTable and ability to download the data csv.
> Add DataTables

- package.json
- src/theme.js
- Add strokeWidth for line charts
- Bump hurumap-ui version
> [HotFix] Update line theme + bumb hurumap-ui

- src/components/ProfilePage.js
- src/theme.js
> [HotFix] Chart and Insight Container Fix

- src/pages/_app.js
Replace script with old method of tracking using ga instead of gtag.
Please delete options that are not relevant.
> Use old google tracking

- src/config.js
Update Ethiopian demographic with data from world bank https://docs.google.com/spreadsheets/d/1SbVBi3819WCD2nffc1snr4opF8JydYfnHlNUaz-2eN8/edit#gid=0
Fixes [#17432876](https://www.pivotaltracker.com/story/show/171432876)
> Update Ethiopian demographic with world bank data

- src/components/SEO.js
Ensure html entities in the structured data are not escaped.
> [Hotfix] SEO Structured Data

- package.json
- yarn.lock
- Bump hurumap-ui version to `0.2.10`
Please delete options that are not relevant.
> Bump hurumap-ui

- src/components/AnalysisPage/getInitialProps.js
- src/components/AnalysisPage/index.js
Scroll to indicator specified by indicatorId into view
*See preview link*
> Scroll indicator to into view

- src/components/AnalysisContent/index.js
- src/components/AnalysisPage/index.js
- src/pages/index.js
- Add lang query to `fetchDefinitionURLs` and other links
> Add language query to URLs

- src/components/Navigation/LanguageSelector.js
main-d413646368613d3242ce.js:1 TypeError: Cannot read property 'toUpperCase' of undefined
at 2a644ff0daa09739814ab27d56dcd9bbf517f972.ea0bfcd3a57189cdd0c2.js:1
at t.value (2a644ff0daa09739814ab27d56dcd9bbf517f972.ea0bfcd3a57189cdd0c2.js:1)
at Va (framework.cd13a438318d678a4f70.js:1)
at ja (framework.cd13a438318d678a4f70.js:1)
at ko (framework.cd13a438318d678a4f70.js:1)
at xu (framework.cd13a438318d678a4f70.js:1)
at wu (framework.cd13a438318d678a4f70.js:1)
at du (framework.cd13a438318d678a4f70.js:1)
at framework.cd13a438318d678a4f70.js:1
at KqkS.t.unstable_runWithPriority (framework.cd13a438318d678a4f70.js:1)
> [Hotfix] default value en

- src/theme.js
Font and collapse table.
https://takwimuafrica-git-fix-tables.takwimu.now.sh/profiles/covid-19/measures-and-restrictions
> Table styles

- package.json
- src/theme.js
- yarn.lock
> Bump HURUmap to Fix Share 

- src/components/AnalysisContent/Actions/index.js
- src/components/AnalysisContent/index.js
We're currently reading last updated from `takwimu.page` this variable however reflects last updated time of Profile/Section and not Topic.
This PR address this.
> [HotFix] Topic last updated

- src/theme.js
> [HotFix] Lists in Cards

- README.md
This follows GNU's suggestion on "How to Apply These Terms to Your New Programs".
> Update README.md license section

- .eslintignore
- next.config.js
- package.json
- src/components/ProfilePage/index.js
- src/pages/_app.js
- src/pages/profiles/[...geoIdOrCountrySlug].js
- src/theme.js
- yarn.lock
Fix long content (and anchors)  overflowing in Snippets. Then a bit of testing revealed:
The above were fixed.
> [HotFix] Snippets

- yarn.lock
Upgrade backward compatible deps to fix some of security warnings.
N/A
> [Chore] Dependencies

- src/components/MaintenanceHero/index.js
> [Fix] Mobile tweaks

- src/pages/[[...slug]].js
> [Fix] Improve offline message
