TakwimuAfrica/Takwimu.AFRICA

- src/components/AnalysisContent/index.js
- src/components/AnalysisContent/topics/CarouselTopic.js
- src/components/DataContainer/EntitiesDataContainer.js
- src/components/DataContainer/FlourishDataContainer.js
- src/components/DataContainer/PDFDataContainer.js
- src/components/DataContainer/index.js
- src/components/FeaturedData.js
Instead of using hard-coded, relative URLs in API and Viz, use the configurable URL e.g. `https://takwimu.africa`
> Use configurable URL in API/Viz calls

- src/components/AnalysisContent/ContentNavigation.js
- src/components/AnalysisContent/OtherInfoNav.js
- src/components/ContentNavigation.js
> Fix Other Info Navigation

- src/data/sources.json
- src/pages/Profile.js
Fixes [#168566062](https://www.pivotaltracker.com/story/show/168566062)
> Show Kenya subnational data

- package.json
- src/config.js
- yarn.lock
When querying total populations table get only one value of the latest year i.e. 2017.
This makes sure [useProfileLoader](https://github.com/CodeForAfrica/HURUmap-UI/blob/a62cacc0498a47432cec137bba23ef047694dd65/src/factory/useProfileLoader/index.js) does not sum up all the years.
The conditions resolves to the following gql which you can test here https://graphql.takwimu.africa/graphiql:
```
{
allTotalPopulations(orderBy: TOTAL_POPULATION_YEAR_DESC, first: 1, condition:{ geoCode: "CD",  geoLevel: "country" } ) {
nodes {
total
}
}
}
```
> Add conditions when querying the total_populations table

- package.json
- pages/index.js
- pages/profiles/[geoIdOrCountrySlug]/index.js
- src/components/AnalysisContent/index.js
- src/components/DataContainer/FlourishChart.js
- src/components/DataContainer/HURUmapChart.js
- src/components/FeaturedData.js
- src/getTakwimuPage.js
- src/pages/Profile.js
- src/utils/getHydrateContent.js
Now that we have **Featured Data** support in `WP`, this PR enables **Featured Data** on the front-end.
NOTE: The appearance of the charts is because of Same-Origin policy prohibiting localhost modifying `iframe` from takwimutech...
> Featured Data

- src/components/AnalysisContent/Actions/DownloadPDF.js
`Download PDF` button doesn't need an ID since it's not a portal; Add link to normal `document`,
> [Hotfix] PDF Download Button ID

- src/components/DataContainer/FlourishChart.js
Theme fonts are not available in the `iframe`.
```
Error while reading CSS rules from https://fonts.googleapis.com/css?family=Lora:400,700|Muli:400,700 SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
```
> [Hotfix] Don't use theme fonts in Flourish iframe

- src/components/AnalysisPage.js
We have moved from using `acf repeater` field to using `acf relationship` field on wordpress for children topics of a profile section. This has in-turn changed the analysis json object structure. This PR updates the `getInitialProps` of analysis-page to correspond with the acf structure changes
Fixes [#170569389](https://www.pivotaltracker.com/story/show/170569389)
> Update Analysis getInitialProps function

- src/components/AnalysisPage.js
- src/components/Footer/StayInTouch.js
- src/components/Footer/Support.js
- src/components/TableOfContent.js
- src/theme.js
> [Hotfix] Analysis page components UI Fixes

- src/components/ProfilePage.js
Customize Insight container to match Takwimu designs
> [Hotfix] Insight Chart Container in Data by Topic pages

- src/components/ProfilePage.js
Re-enables embed button on **Data by Topic** pages
> [Hofix] Embed button

- src/components/AnalysisContent/Actions/DownloadPDF.js
- src/components/Footer/index.js
- src/components/MakingOfTakwimu.js
> [Hotfix] Year of Takwimu

- src/components/ProfilePage.js
Takwimu designs doesn't seem to be using dependent (y-axis) charts and until we can add ability to tweak per chart appearance in the dashboard, it's best to not show them
> [Hotfix] dependent Axis labels

- src/components/SearchResults/DataSearchResultItem.js
URL given for data results when found in analysis pages was incorrect; hash was put before query making query inaccessible to SSR. This PR fixes the structure to `/path?query#hash`.
N/A
> [Hotfix] URL Structure

- src/components/CountryContent/index.js
- src/components/Next/Analysis.js
- src/theme.js
> [Hotfix] Analysis Page Spacing and Chart Grid

- src/components/AnalysisPage.js
- src/config.js
This PR introduces a hierarchy of languages in Takwimu: Site wide default and (country) profile default. This is to support those countries that are predominantly non-English speaking. Their country profiles should by default be presented in their native language.
#96 will allow users to switch to other supported languages.
Fixes #171484798
> Hierarchical Language Support

- src/pages/_document.js
Integrate [Takwimu.AFRICA](https://takwimu.africa) with CRM so that we know when our contacts visit the site.
> Integrate with CRM

- src/components/FeaturedAnalysis/index.js
- src/components/utils.js
The current `countrify` behaviour of appending `'s` to country names is only correct for `en`. Now that we support multiple languages, we should restring this behaviour to English only _for now_. 
Future versions may come up with per language `countrification`.
Delivers #171810557
> Countrify based on language

- .gitignore
- next.config.js
- package.json
- src/components/AnalysisContent/index.js
- src/components/AnalysisPage/getInitialProps.js
- src/components/AnalysisPage/index.js
- src/components/Navigation/index.js
- src/components/ProfilePage/index.js
- src/components/SearchInput/Input.js
- src/pages/404.js
- src/pages/_error.js
- src/pages/embed/[...path].js
- src/pages/profiles/[...geoIdOrCountrySlug].js
- yarn.lock
The content team needs ability to add dynamic profiles to the CMS without requiring TECH team's help.
Nextjs has all introduce [`Catch all routes`](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes) which changes how dynamic routes works.
This PR upgrades our dynamic routing mechanism as well as enable dynamic profiles that do not need a specific country. 
ASIDE: Next.js now requires 404 error page be static and in a `404.js` file... `_error.js` remains for other "dynamic" errors.
> Catch all routes + Dynamic Profiles

- src/components/utils.js
- src/config.js
Content team has opted for use of `:` as a separator for _all languages_ e.g. **Kenya: Development Context**
This PR makes the change above as well as translate country names to French whenever and wherever applicable.
> Use `:` as separator

- src/pages/_app.js
Font loading fails when downloading/sharing iframe due to security issues. This PR adds a permissive Content Security Policy to try and resolve that issue.
N/A
> [Investigative] Add Permissive CSP to Test iframe font Loading Issue

- src/pages/_app.js
Looks like Content Security Policy won't help with iframe font loading issue: Essential we have no control of the html content from the iframe and it loads google font without setting `crossorign="anonymous"`
https://github.com/tsayen/dom-to-image/issues/205#issuecomment-512328517
Please delete options that are not relevant.
N/A
> [Investigative] Remove CSP

- src/components/LatestNewsStories/StoryBlocks.js
- src/components/LatestNewsStories/StoryList.js
- src/pages/index.js
- src/utils/fetchStories.js
Remove usage of stories.hurumap.org when fetching latest stories. Fetch stories directly from source.
> [HotFix] Remove Usage of stories.hurumap.org
